#!/usr/bin/env node

import 'make-promises-safe';
import { Buffer } from 'buffer';
import minimist from 'minimist';
import concat from 'concat-stream';
import explain from 'explain-error';
import announce from 'u-wave-announce';
import ytSource from 'u-wave-source-youtube';
import scSource from 'u-wave-source-soundcloud';
import recaptchaTestKeys from 'recaptcha-test-keys';
import createDebug from 'debug';
import dotenv from 'dotenv';

const debug = createDebug('uwave:dev-server');
const argv = minimist(process.argv.slice(2));

dotenv.config();

const testTransport = {
  name: 'test',
  version: '0.0.0',
  send(mail, callback) {
    mail.message.createReadStream().pipe(concat((message) => {
      debug(mail.message.getEnvelope().to, message.toString('utf8'));
      callback(null, {
        envelope: mail.message.getEnvelope(),
        messageId: mail.message.messageId(),
      });
    }));
  },
};

/**
 * üWave API development server.
 */
async function start() {
  const port = Number(argv.port || process.env.PORT || 6042);

  const uwave = await import('u-wave-core');

  const secret = Buffer.from('none', 'utf8');

  const uw = uwave({
    port,
    redis: process.env.REDIS_URL,
    mongo: process.env.MONGODB_URL ?? 'mongodb://localhost/uwave',
    secret,
    mailTransport: testTransport,
    timeout: 10,
  });

  uw.use(async function configureExpress(uw) {
    uw.express.set('json spaces', 2);
  });

  uw.on('mongoError', (err) => {
    throw explain(err, 'Could not connect to MongoDB. Is it installed and running?');
  });

  uw.on('redisError', (err) => {
    throw explain(err, 'Could not connect to the Redis server. Is it installed and running?');
  });

  uw.use(announce, {
    // Omit this in a real app: it will auto-generate one for you.
    seed: Buffer.from('8286a5e55c62d93a042b8c56c8face52c05354c288807d941751f0e9060c2ded', 'hex'),
  });

  uw.use(async function configureSources(uw) {
    if (process.env.YOUTUBE_API_KEY) {
      uw.source(ytSource, {
        key: process.env.YOUTUBE_API_KEY,
      });
    }
    uw.source(scSource, {
      key: process.env.SOUNDCLOUD_API_KEY,
    });
  });

  await uw.listen();
  console.log(`Now listening on ${port}`);
}

start().catch((error) => {
  console.error(error.stack);
  process.exit(1);
});
